# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c549e6d38a656a012e7fd412adb11460"
name = "Getoify-6"
application_url = "https://www.getoify.com"
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = ""

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products,write_products,read_script_tags,write_script_tags,read_content,write_content,read_translations,write_translations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://www.getoify.com/auth/callback",
  "https://getoify.vercel.app/auth/callback",
  "https://getoify.onrender.com/auth/callback"
]
